### ISSUE TITLE
Allow control over which `GraphState` operations are depicted by server

### ISSUE THREAD

**Issue by SLesslyTall** [peteshadbolt/abp#8]
I keep finding a curious bug where a number of operations previously performed on an instance of `GraphState` are displayed on the server after the last usage of `GraphState` or `gs.update()` in the code. This is frustrating as it prevents a 'final state' of the code being depicted visually, instead replaced by some previously and unrelated instance of `GraphState`. The depiction of all the interstitial `GraphState` instances (always depicted post-measurement, for some reason) is also slowing the execution of the code as it must wait to cycle through all interstitial depictions, each pausing on each for 0.5s.

It would therefore be useful to be able to decide which instances of `GraphState` are pushed to the server, as it seems to be a problem that only occurs when the server is not active.

**Comment by peteshadbolt** [comment]
Can you provide a working example? Sounds like it might be a networking / ordering problem.

Note that you can call `update()` as frequently or infrequently as you like - if you just want to see the final state, you don't actually have to call it at all (`fancy.GraphState` calls `update()` automatically at the end of your program)

**Comment by peteshadbolt** [comment]
In fact - I have a good guess as to exactly why this is happening. If you instantiate two different `fancy.GraphStates` at once, `a` and `b`, then they both add a hook to send their state to the server at the end of the program. Which one is actually displayed is likely to be random, as they both try to send at exactly the same time.

A proposed fix would be to remove that hook. Downside is that you can't write lazy programs which don't call `update()` - but that's probably a price worth paying.

**Comment by SLesslyTall** [comment]
Yeah, I thought it might be something to do with how the object interacts with the server at the end of the program (caused by the garbage collector mechanism?). I think that removing the `update()` would be a good fix. I tried to look for something like that in the source code, but couldn't find the offending line.
