### ISSUE TITLE
Add ability to specify the 'friend' of a node for 'GraphState' method 'measure'

### ISSUE THREAD

**Issue by SLesslyTall** [peteshadbolt/abp#9]
Suggested change: add optional argument `friend=None` to `GraphState` method  `_measure_graph_x`, `measure_x` and `measure`, that allows the user to specify which node is chosen as the "friend".

**Comment by peteshadbolt** [comment]
Yeah I guess this is useful when you want to control the representation. Don't see any problem with it. `_measure_graph_x` is pretty ugly as is. @SLesslyTall can you write a test that shows your requirements here? I can write the patch.

**Comment by peteshadbolt** [comment]
[Done](https://github.com/peteshadbolt/abp/commit/110312a89789ea12eabdb2d0b432824b1753f66d)
